services:
  netpatrol:
    build: .
    container_name: netpatrol
    restart: always
    # CRITICAL: Host networking and privileged mode ensure nmap has full visibility
    network_mode: host
    privileged: true
    volumes:
      - netpatrol_db:/app/prisma
    env_file:
      - .env

volumes:
  netpatrol_db:
